// ─── Seed Data: 12 customers, 40+ tickets, 6 months of history ──────────────
// All data is synthetic. No real customer PII.

import type {
  Customer,
  Ticket,
  EpisodicMemory,
  SemanticMemory,
  ProceduralMemory,
  AffectiveMemory,
  WinningFix,
  FailedSolution,
  FrustrationLevel,
  AnalyticsData,
} from './types';

// ─── Customers ───────────────────────────────────────────────────────────────

export const customers: Customer[] = [
  {
    id: 'CUST-1001',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    plan: 'Business',
    avatar: 'PS',
    environment: {
      os: 'Windows 11',
      browser: 'Chrome 140',
      appVersion: '4.5.2',
      device: 'Desktop',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'intermediate',
      preferredTone: 'concise',
      language: 'en',
    },
    joinedDate: '2025-11-15',
    totalTickets: 8,
    lifetimeValue: 4800,
  },
  {
    id: 'CUST-1002',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@example.com',
    plan: 'Enterprise',
    avatar: 'RM',
    environment: {
      os: 'macOS 15.2',
      browser: 'Safari 19',
      appVersion: '4.5.2',
      device: 'MacBook Pro',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'email',
      technicalLevel: 'power-user',
      preferredTone: 'detailed',
      language: 'en',
    },
    joinedDate: '2025-06-01',
    totalTickets: 5,
    lifetimeValue: 12000,
  },
  {
    id: 'CUST-1003',
    name: 'Ananya Rao',
    email: 'ananya.rao@example.com',
    plan: 'Pro',
    avatar: 'AR',
    environment: {
      os: 'Windows 11',
      browser: 'Chrome 140',
      appVersion: '4.5.2',
      device: 'Desktop',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'intermediate',
      preferredTone: 'professional',
      language: 'en',
    },
    joinedDate: '2025-09-20',
    totalTickets: 4,
    lifetimeValue: 2400,
  },
  {
    id: 'CUST-1004',
    name: 'Vikram Patel',
    email: 'vikram.patel@example.com',
    plan: 'Starter',
    avatar: 'VP',
    environment: {
      os: 'Android 16',
      browser: 'Chrome Mobile',
      appVersion: '4.2.0',
      device: 'Pixel 9',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'phone',
      technicalLevel: 'non-technical',
      preferredTone: 'casual',
      language: 'en',
    },
    joinedDate: '2026-01-10',
    totalTickets: 6,
    lifetimeValue: 600,
  },
  {
    id: 'CUST-1005',
    name: 'Deepika Nair',
    email: 'deepika.nair@example.com',
    plan: 'Business',
    avatar: 'DN',
    environment: {
      os: 'macOS 15.1',
      browser: 'Firefox 135',
      appVersion: '4.5.2',
      device: 'MacBook Air',
      timezone: 'America/New_York',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'technical',
      preferredTone: 'professional',
      language: 'en',
    },
    joinedDate: '2025-08-05',
    totalTickets: 3,
    lifetimeValue: 4800,
  },
  {
    id: 'CUST-1006',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@example.com',
    plan: 'Enterprise',
    avatar: 'ARE',
    environment: {
      os: 'Ubuntu 24.04',
      browser: 'Chrome 140',
      appVersion: '4.5.2',
      device: 'Desktop',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'power-user',
      preferredTone: 'concise',
      language: 'en',
    },
    joinedDate: '2025-05-15',
    totalTickets: 4,
    lifetimeValue: 15000,
  },
  {
    id: 'CUST-1007',
    name: 'Meera Joshi',
    email: 'meera.joshi@example.com',
    plan: 'Pro',
    avatar: 'MJ',
    environment: {
      os: 'iOS 19',
      browser: 'Safari Mobile',
      appVersion: '4.5.1',
      device: 'iPhone 17',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'intermediate',
      preferredTone: 'casual',
      language: 'en',
    },
    joinedDate: '2025-12-01',
    totalTickets: 3,
    lifetimeValue: 1800,
  },
  {
    id: 'CUST-1008',
    name: 'Karthik Iyer',
    email: 'karthik.iyer@example.com',
    plan: 'Business',
    avatar: 'KI',
    environment: {
      os: 'Windows 11',
      browser: 'Edge 140',
      appVersion: '4.5.2',
      device: 'Desktop',
      timezone: 'Europe/London',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'email',
      technicalLevel: 'technical',
      preferredTone: 'detailed',
      language: 'en',
    },
    joinedDate: '2025-07-20',
    totalTickets: 3,
    lifetimeValue: 6000,
  },
  {
    id: 'CUST-1009',
    name: 'Sanya Gupta',
    email: 'sanya.gupta@example.com',
    plan: 'Starter',
    avatar: 'SG',
    environment: {
      os: 'Android 15',
      browser: 'Chrome Mobile',
      appVersion: '4.2.0',
      device: 'Samsung Galaxy S25',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'non-technical',
      preferredTone: 'casual',
      language: 'en',
    },
    joinedDate: '2026-03-01',
    totalTickets: 2,
    lifetimeValue: 300,
  },
  {
    id: 'CUST-1010',
    name: 'Rohan Das',
    email: 'rohan.das@example.com',
    plan: 'Pro',
    avatar: 'RD',
    environment: {
      os: 'macOS 15.2',
      browser: 'Chrome 140',
      appVersion: '4.5.2',
      device: 'iMac',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'technical',
      preferredTone: 'concise',
      language: 'en',
    },
    joinedDate: '2025-10-15',
    totalTickets: 3,
    lifetimeValue: 3600,
  },
  {
    id: 'CUST-1011',
    name: 'Lakshmi Venkat',
    email: 'lakshmi.venkat@example.com',
    plan: 'Enterprise',
    avatar: 'LV',
    environment: {
      os: 'Windows 11',
      browser: 'Chrome 140',
      appVersion: '4.5.2',
      device: 'Desktop',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'email',
      technicalLevel: 'intermediate',
      preferredTone: 'professional',
      language: 'en',
    },
    joinedDate: '2025-04-10',
    totalTickets: 2,
    lifetimeValue: 18000,
  },
  {
    id: 'CUST-1012',
    name: 'Amit Saxena',
    email: 'amit.saxena@example.com',
    plan: 'Business',
    avatar: 'AS',
    environment: {
      os: 'Android 16',
      browser: 'Chrome Mobile',
      appVersion: '4.5.0',
      device: 'OnePlus 14',
      timezone: 'Asia/Kolkata',
      language: 'en',
    },
    communicationStyle: {
      preferredChannel: 'chat',
      technicalLevel: 'intermediate',
      preferredTone: 'casual',
      language: 'en',
    },
    joinedDate: '2025-11-25',
    totalTickets: 2,
    lifetimeValue: 4200,
  },
];

// ─── Tickets (40+) ──────────────────────────────────────────────────────────

export const tickets: Ticket[] = [
  // ── Priya Sharma: Hero customer, 4th billing-sync, 3 failed fixes, 1 that worked ──
  {
    id: 'TKT-4818',
    customerId: 'CUST-1001',
    subject: 'Billing sync not reflecting payment',
    category: 'billing',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-04-11T18:00:00Z',
    createdAt: '2026-04-10T09:15:00Z',
    updatedAt: '2026-04-11T14:30:00Z',
    resolvedAt: '2026-04-11T14:30:00Z',
    resolution: 'Cleared billing cache and forced sync from payment gateway.',
    messages: [
      { id: 'm1', role: 'customer', content: 'My payment went through but the dashboard still shows unpaid. This is the first time this has happened.', timestamp: '2026-04-10T09:15:00Z' },
      { id: 'm2', role: 'agent', content: 'I can see your payment was processed. Let me force a billing sync for your account. This should update within a few minutes.', timestamp: '2026-04-10T09:22:00Z' },
      { id: 'm3', role: 'customer', content: 'It updated now. Thanks!', timestamp: '2026-04-10T09:45:00Z' },
    ],
    tags: ['billing', 'sync', 'payment'],
  },
  {
    id: 'TKT-4821',
    customerId: 'CUST-1001',
    subject: 'Billing sync failed again after plan upgrade',
    category: 'billing',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'warning',
    slaDeadline: '2026-05-16T18:00:00Z',
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-05-16T16:00:00Z',
    resolvedAt: '2026-05-16T16:00:00Z',
    resolution: 'Tried clearing cache (failed), tried re-linking payment method (failed). Escalated to billing team who found a webhook race condition.',
    messages: [
      { id: 'm4', role: 'customer', content: 'Same billing sync issue as last month. I upgraded my plan and the payment shows in my bank but not in the app.', timestamp: '2026-05-15T10:00:00Z' },
      { id: 'm5', role: 'agent', content: 'I see this happened before. Let me try clearing the billing cache again like last time.', timestamp: '2026-05-15T10:10:00Z' },
      { id: 'm6', role: 'customer', content: 'It did not work this time.', timestamp: '2026-05-15T10:30:00Z' },
      { id: 'm7', role: 'agent', content: 'Let me try re-linking your payment method. Please go to Settings > Payment and click "Re-link".', timestamp: '2026-05-15T10:35:00Z' },
      { id: 'm8', role: 'customer', content: 'Done, still showing unpaid. This is frustrating.', timestamp: '2026-05-15T11:00:00Z' },
      { id: 'm9', role: 'agent', content: 'I understand your frustration. I am escalating this to our billing team. They found a webhook race condition and are fixing it now.', timestamp: '2026-05-15T11:05:00Z' },
      { id: 'm10', role: 'customer', content: 'Finally resolved. Thank you for escalating.', timestamp: '2026-05-16T16:00:00Z' },
    ],
    tags: ['billing', 'sync', 'escalation', 'webhook'],
  },
  {
    id: 'TKT-4830',
    customerId: 'CUST-1001',
    subject: 'Billing sync broken again - third time',
    category: 'billing',
    status: 'resolved',
    priority: 'critical',
    slaStatus: 'breached',
    slaDeadline: '2026-07-03T18:00:00Z',
    createdAt: '2026-07-02T08:00:00Z',
    updatedAt: '2026-07-04T10:00:00Z',
    resolvedAt: '2026-07-04T10:00:00Z',
    resolution: 'Applied server-side billing reconciliation script. Webhook issue was a different root cause from TKT-4821.',
    messages: [
      { id: 'm11', role: 'customer', content: 'AGAIN? My billing is not syncing AGAIN. This is the third time. I am losing patience.', timestamp: '2026-07-02T08:00:00Z' },
      { id: 'm12', role: 'agent', content: 'I sincerely apologize. I can see this is the third occurrence. Previous fixes (cache clear, re-link, webhook fix) were attempted. Let me try the billing reconciliation script directly.', timestamp: '2026-07-02T08:10:00Z' },
      { id: 'm13', role: 'customer', content: 'Please just fix it permanently.', timestamp: '2026-07-02T08:15:00Z' },
      { id: 'm14', role: 'agent', content: 'The reconciliation script has been applied. Your account now shows the correct payment status. I have also flagged your account for priority billing monitoring.', timestamp: '2026-07-02T09:30:00Z' },
      { id: 'm15', role: 'customer', content: 'OK, I can see it now. But I need this to stop happening.', timestamp: '2026-07-02T09:45:00Z' },
    ],
    tags: ['billing', 'sync', 'recurring', 'frustrated'],
  },
  {
    id: 'TKT-4845',
    customerId: 'CUST-1001',
    subject: 'Billing sync issue - 4th occurrence',
    category: 'billing',
    status: 'open',
    priority: 'critical',
    slaStatus: 'warning',
    slaDeadline: '2026-09-29T18:00:00Z',
    createdAt: '2026-09-28T14:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
    messages: [
      { id: 'm16', role: 'customer', content: 'I cannot believe this. My billing is out of sync FOR THE FOURTH TIME. I have been a paying customer for almost a year. Cache clearing did not work. Re-linking did not work. Your webhook fix did not last. The reconciliation script only worked once. I need a permanent solution or I am switching to a competitor.', timestamp: '2026-09-28T14:00:00Z' },
    ],
    tags: ['billing', 'sync', 'recurring', 'churn-risk', 'frustrated'],
  },
  // Priya: other tickets
  {
    id: 'TKT-4819',
    customerId: 'CUST-1001',
    subject: 'Dashboard loading slowly',
    category: 'performance',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-04-20T18:00:00Z',
    createdAt: '2026-04-18T11:00:00Z',
    updatedAt: '2026-04-19T09:00:00Z',
    resolvedAt: '2026-04-19T09:00:00Z',
    resolution: 'CDN cache invalidated for user region.',
    messages: [
      { id: 'm17', role: 'customer', content: 'Dashboard takes 15 seconds to load. It used to be fast.', timestamp: '2026-04-18T11:00:00Z' },
      { id: 'm18', role: 'agent', content: 'I invalidated the CDN cache for your region. Please try reloading.', timestamp: '2026-04-18T11:20:00Z' },
      { id: 'm19', role: 'customer', content: 'Much faster now, thanks.', timestamp: '2026-04-18T11:25:00Z' },
    ],
    tags: ['performance', 'dashboard'],
  },
  {
    id: 'TKT-4822',
    customerId: 'CUST-1001',
    subject: 'CSV export missing columns',
    category: 'export',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-06-02T18:00:00Z',
    createdAt: '2026-05-30T09:00:00Z',
    updatedAt: '2026-05-31T10:00:00Z',
    resolvedAt: '2026-05-31T10:00:00Z',
    resolution: 'Custom column mapping was reset after plan upgrade. Re-configured.',
    messages: [
      { id: 'm20', role: 'customer', content: 'My CSV exports are missing the "region" and "status" columns since I upgraded.', timestamp: '2026-05-30T09:00:00Z' },
      { id: 'm21', role: 'agent', content: 'Plan upgrades can reset custom column mappings. I have restored your configuration. Try exporting again.', timestamp: '2026-05-30T09:15:00Z' },
      { id: 'm22', role: 'customer', content: 'All columns are back. Thank you.', timestamp: '2026-05-30T09:30:00Z' },
    ],
    tags: ['export', 'csv', 'plan-upgrade'],
  },
  {
    id: 'TKT-4835',
    customerId: 'CUST-1001',
    subject: 'Two-factor authentication not sending codes',
    category: 'authentication',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-08-11T18:00:00Z',
    createdAt: '2026-08-10T07:00:00Z',
    updatedAt: '2026-08-10T08:30:00Z',
    resolvedAt: '2026-08-10T08:30:00Z',
    resolution: 'SMS provider throttling resolved; switched to authenticator app.',
    messages: [
      { id: 'm23', role: 'customer', content: 'I am not receiving 2FA codes via SMS. Cannot log in.', timestamp: '2026-08-10T07:00:00Z' },
      { id: 'm24', role: 'agent', content: 'Our SMS provider is experiencing delays. I recommend switching to an authenticator app for more reliable 2FA.', timestamp: '2026-08-10T07:10:00Z' },
      { id: 'm25', role: 'customer', content: 'Set up authenticator. Works now.', timestamp: '2026-08-10T08:30:00Z' },
    ],
    tags: ['authentication', '2fa', 'sms'],
  },

  // ── Rahul Mehta: calm technical power user ──
  {
    id: 'TKT-4823',
    customerId: 'CUST-1002',
    subject: 'API rate limiting not matching documentation',
    category: 'api',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-05-20T18:00:00Z',
    createdAt: '2026-05-18T14:00:00Z',
    updatedAt: '2026-05-19T11:00:00Z',
    resolvedAt: '2026-05-19T11:00:00Z',
    resolution: 'Documentation was outdated. Updated rate limits and provided correct headers.',
    messages: [
      { id: 'm26', role: 'customer', content: 'The API docs say 1000 req/min for Enterprise, but I am getting 429s at 500 req/min. Here is my test script output.', timestamp: '2026-05-18T14:00:00Z' },
      { id: 'm27', role: 'agent', content: 'You are right — the docs were outdated. Enterprise gets 800 req/min on the current plan. I have updated the docs and increased your limit to 1200 as a goodwill gesture. Use the X-RateLimit-Remaining header to track.', timestamp: '2026-05-18T14:30:00Z' },
      { id: 'm28', role: 'customer', content: 'Confirmed working at 1200. Thanks for the quick and detailed response.', timestamp: '2026-05-19T11:00:00Z' },
    ],
    tags: ['api', 'rate-limit', 'documentation'],
  },
  {
    id: 'TKT-4826',
    customerId: 'CUST-1002',
    subject: 'Webhook signatures not validating',
    category: 'api',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-06-14T18:00:00Z',
    createdAt: '2026-06-12T09:00:00Z',
    updatedAt: '2026-06-13T10:00:00Z',
    resolvedAt: '2026-06-13T10:00:00Z',
    resolution: 'Webhook secret was rotated but old secret was cached. Provided new secret.',
    messages: [
      { id: 'm29', role: 'customer', content: 'HMAC validation is failing on all webhook payloads since yesterday. I double-checked my verification code. Here is a sample payload and expected signature.', timestamp: '2026-06-12T09:00:00Z' },
      { id: 'm30', role: 'agent', content: 'I can see your webhook secret was auto-rotated during a security update. Here is your new secret: wh_sec_***. I recommend storing it in your env vars.', timestamp: '2026-06-12T09:20:00Z' },
      { id: 'm31', role: 'customer', content: 'Updated and validating correctly. Would be nice to get notified on secret rotation.', timestamp: '2026-06-13T10:00:00Z' },
    ],
    tags: ['api', 'webhook', 'security'],
  },
  {
    id: 'TKT-4831',
    customerId: 'CUST-1002',
    subject: 'GraphQL query performance degradation',
    category: 'api',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-07-12T18:00:00Z',
    createdAt: '2026-07-10T15:00:00Z',
    updatedAt: '2026-07-11T09:00:00Z',
    resolvedAt: '2026-07-11T09:00:00Z',
    resolution: 'Recommended query optimization with field selection and pagination.',
    messages: [
      { id: 'm32', role: 'customer', content: 'My GraphQL queries are taking 8+ seconds. They used to complete in under 1s. Running same queries, no changes on my end.', timestamp: '2026-07-10T15:00:00Z' },
      { id: 'm33', role: 'agent', content: 'I see you are fetching all fields on nested relations. Since our last schema update, I recommend: 1) Use field selection to only request needed fields. 2) Add cursor pagination with limit 50. Here is an optimized example query.', timestamp: '2026-07-10T15:30:00Z' },
      { id: 'm34', role: 'customer', content: 'Down to 200ms with those optimizations. Well done.', timestamp: '2026-07-11T09:00:00Z' },
    ],
    tags: ['api', 'graphql', 'performance'],
  },
  {
    id: 'TKT-4840',
    customerId: 'CUST-1002',
    subject: 'SSO SAML configuration failing',
    category: 'authentication',
    status: 'open',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-27T10:00:00Z',
    updatedAt: '2026-09-28T10:00:00Z',
    messages: [
      { id: 'm35', role: 'customer', content: 'Setting up SAML SSO with Okta. Getting "Invalid Assertion" error. Here is my IdP metadata XML and the error log.', timestamp: '2026-09-27T10:00:00Z' },
      { id: 'm36', role: 'agent', content: 'Based on your metadata, the Audience URI needs to match exactly: https://app.example.com/saml/consume. Also ensure clock skew tolerance is set to 5 minutes in Okta.', timestamp: '2026-09-27T10:30:00Z' },
      { id: 'm37', role: 'customer', content: 'Updated the Audience URI but still failing. New error: "Signature validation failed".', timestamp: '2026-09-28T10:00:00Z' },
    ],
    tags: ['authentication', 'sso', 'saml', 'okta'],
  },

  // ── Ananya Rao ──
  {
    id: 'TKT-4820',
    customerId: 'CUST-1003',
    subject: 'Checkout failing with error PAY-204',
    category: 'payments',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-04-16T18:00:00Z',
    createdAt: '2026-04-14T13:00:00Z',
    updatedAt: '2026-04-14T14:00:00Z',
    resolvedAt: '2026-04-14T14:00:00Z',
    resolution: 'Browser extension conflict. Disabling extension fixed checkout.',
    messages: [
      { id: 'm38', role: 'customer', content: 'Checkout is failing with error PAY-204. Cannot complete purchase.', timestamp: '2026-04-14T13:00:00Z' },
      { id: 'm39', role: 'agent', content: 'This error often occurs due to browser extension conflicts. Could you try disabling extensions and retrying?', timestamp: '2026-04-14T13:10:00Z' },
      { id: 'm40', role: 'customer', content: 'Disabled an ad-blocker and it worked. Thanks!', timestamp: '2026-04-14T14:00:00Z' },
    ],
    tags: ['payments', 'checkout', 'browser-extension'],
  },
  {
    id: 'TKT-4828',
    customerId: 'CUST-1003',
    subject: 'Checkout error PAY-204 returned',
    category: 'payments',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-06-22T18:00:00Z',
    createdAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-06-20T11:00:00Z',
    resolvedAt: '2026-06-20T11:00:00Z',
    resolution: 'Same browser extension conflict. Customer re-enabled the ad-blocker.',
    messages: [
      { id: 'm41', role: 'customer', content: 'PAY-204 error again during checkout.', timestamp: '2026-06-20T10:00:00Z' },
      { id: 'm42', role: 'agent', content: 'I see this happened before with an ad-blocker. Have you re-enabled it?', timestamp: '2026-06-20T10:05:00Z' },
      { id: 'm43', role: 'customer', content: 'Yes, I had. Disabled it and checkout works again.', timestamp: '2026-06-20T11:00:00Z' },
    ],
    tags: ['payments', 'checkout', 'browser-extension', 'recurring'],
  },
  {
    id: 'TKT-4832',
    customerId: 'CUST-1003',
    subject: 'Notification preferences not saving',
    category: 'settings',
    status: 'resolved',
    priority: 'low',
    slaStatus: 'within',
    slaDeadline: '2026-07-18T18:00:00Z',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-16T10:00:00Z',
    resolvedAt: '2026-07-16T10:00:00Z',
    resolution: 'Browser cookie issue. Clearing cookies and re-saving fixed it.',
    messages: [
      { id: 'm44', role: 'customer', content: 'Every time I change notification preferences, they revert back after I refresh.', timestamp: '2026-07-15T09:00:00Z' },
      { id: 'm45', role: 'agent', content: 'This is usually a cookie issue. Please clear your browser cookies for our site and try again.', timestamp: '2026-07-15T09:15:00Z' },
      { id: 'm46', role: 'customer', content: 'Cleared cookies and preferences are saving now.', timestamp: '2026-07-16T10:00:00Z' },
    ],
    tags: ['settings', 'notifications', 'cookies'],
  },
  {
    id: 'TKT-4843',
    customerId: 'CUST-1003',
    subject: 'Data export timing out',
    category: 'export',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-26T11:00:00Z',
    updatedAt: '2026-09-27T09:00:00Z',
    messages: [
      { id: 'm47', role: 'customer', content: 'Trying to export 6 months of data and it keeps timing out at 80%.', timestamp: '2026-09-26T11:00:00Z' },
      { id: 'm48', role: 'agent', content: 'Large exports can time out. Try exporting in 1-month chunks, or I can generate a background export link for you.', timestamp: '2026-09-26T11:15:00Z' },
      { id: 'm49', role: 'customer', content: 'Background export would be great. Can you set that up?', timestamp: '2026-09-27T09:00:00Z' },
    ],
    tags: ['export', 'timeout', 'large-data'],
  },

  // ── Vikram Patel: non-technical, prefers phone, app update caused regression ──
  {
    id: 'TKT-4824',
    customerId: 'CUST-1004',
    subject: 'App crashes after opening',
    category: 'mobile',
    status: 'resolved',
    priority: 'critical',
    slaStatus: 'within',
    slaDeadline: '2026-05-22T18:00:00Z',
    createdAt: '2026-05-20T08:00:00Z',
    updatedAt: '2026-05-21T10:00:00Z',
    resolvedAt: '2026-05-21T10:00:00Z',
    resolution: 'App version 4.2 had a known crash bug on Android 16. Updated to 4.3 fixed it.',
    messages: [
      { id: 'm50', role: 'customer', content: 'The app just closes immediately after I open it. I have not changed anything on my phone.', timestamp: '2026-05-20T08:00:00Z' },
      { id: 'm51', role: 'agent', content: 'I see you are on app version 4.2. There is a known crash issue on Android 16 with this version. Please update to version 4.3 from the Play Store.', timestamp: '2026-05-20T08:15:00Z' },
      { id: 'm52', role: 'customer', content: 'Updated and it opens fine now. Why did this happen?', timestamp: '2026-05-21T10:00:00Z' },
      { id: 'm53', role: 'agent', content: 'Version 4.2 had a compatibility issue with the new Android 16 permissions system. Version 4.3 fixed that. Sorry for the trouble!', timestamp: '2026-05-21T10:10:00Z' },
    ],
    tags: ['mobile', 'crash', 'android', 'app-version'],
  },
  {
    id: 'TKT-4827',
    customerId: 'CUST-1004',
    subject: 'Cannot find the settings menu',
    category: 'usability',
    status: 'resolved',
    priority: 'low',
    slaStatus: 'within',
    slaDeadline: '2026-06-10T18:00:00Z',
    createdAt: '2026-06-08T15:00:00Z',
    updatedAt: '2026-06-08T15:30:00Z',
    resolvedAt: '2026-06-08T15:30:00Z',
    resolution: 'Guided user to settings via hamburger menu.',
    messages: [
      { id: 'm54', role: 'customer', content: 'Where is the settings menu? I cannot find it anywhere. The app looks different after the update.', timestamp: '2026-06-08T15:00:00Z' },
      { id: 'm55', role: 'agent', content: 'After the 4.3 update, settings moved to the hamburger menu (three lines icon) at the top-left. Tap it, then tap "Settings" at the bottom of the menu.', timestamp: '2026-06-08T15:10:00Z' },
      { id: 'm56', role: 'customer', content: 'Found it! Thank you. I wish you would not keep moving things around.', timestamp: '2026-06-08T15:30:00Z' },
    ],
    tags: ['usability', 'mobile', 'navigation'],
  },
  {
    id: 'TKT-4833',
    customerId: 'CUST-1004',
    subject: 'Push notifications stopped working after update to 4.5',
    category: 'mobile',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'warning',
    slaDeadline: '2026-07-22T18:00:00Z',
    createdAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-07-22T16:00:00Z',
    resolvedAt: '2026-07-22T16:00:00Z',
    resolution: 'App update 4.5 reset notification permissions. Guided user to re-enable.',
    messages: [
      { id: 'm57', role: 'customer', content: 'I updated the app to version 4.5 and now I am not getting any notifications at all. I was getting them before.', timestamp: '2026-07-20T09:00:00Z' },
      { id: 'm58', role: 'agent', content: 'The 4.5 update sometimes resets notification permissions. Go to your phone Settings > Apps > our app > Notifications and make sure they are turned on.', timestamp: '2026-07-20T09:15:00Z' },
      { id: 'm59', role: 'customer', content: 'I turned them on but I am still not getting notifications for new messages.', timestamp: '2026-07-21T10:00:00Z' },
      { id: 'm60', role: 'agent', content: 'Also check that battery optimization is disabled for our app. Go to Settings > Battery > App battery usage > our app > "Unrestricted".', timestamp: '2026-07-21T10:15:00Z' },
      { id: 'm61', role: 'customer', content: 'OK I did that. I will wait and see if notifications come through now.', timestamp: '2026-07-22T10:00:00Z' },
      { id: 'm62', role: 'customer', content: 'Got a notification! Thank you.', timestamp: '2026-07-22T16:00:00Z' },
    ],
    tags: ['mobile', 'notifications', 'app-version', 'permissions'],
  },
  {
    id: 'TKT-4838',
    customerId: 'CUST-1004',
    subject: 'Photos not uploading in chat',
    category: 'mobile',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-08-28T18:00:00Z',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-26T09:00:00Z',
    resolvedAt: '2026-08-26T09:00:00Z',
    resolution: 'Storage permission was revoked after app update. Re-granted permission.',
    messages: [
      { id: 'm63', role: 'customer', content: 'I cannot attach photos in chat anymore. Nothing happens when I tap the camera icon.', timestamp: '2026-08-25T11:00:00Z' },
      { id: 'm64', role: 'agent', content: 'This sounds like a permissions issue after the app update. Go to Settings > Apps > our app > Permissions and make sure "Photos and videos" and "Camera" are allowed.', timestamp: '2026-08-25T11:15:00Z' },
      { id: 'm65', role: 'customer', content: 'That worked! Why does every update break something?', timestamp: '2026-08-26T09:00:00Z' },
    ],
    tags: ['mobile', 'permissions', 'uploads', 'app-version'],
  },
  {
    id: 'TKT-4844',
    customerId: 'CUST-1004',
    subject: 'App very slow after latest update',
    category: 'mobile',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-10-01T18:00:00Z',
    createdAt: '2026-09-28T12:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
    messages: [
      { id: 'm66', role: 'customer', content: 'The app is really slow now. Every screen takes forever to load. I am still on my old Pixel 9.', timestamp: '2026-09-28T12:00:00Z' },
    ],
    tags: ['mobile', 'performance', 'app-version'],
  },

  // ── Deepika Nair ──
  {
    id: 'TKT-4825',
    customerId: 'CUST-1005',
    subject: 'Integration with Slack not delivering messages',
    category: 'integrations',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-05-24T18:00:00Z',
    createdAt: '2026-05-22T10:00:00Z',
    updatedAt: '2026-05-23T09:00:00Z',
    resolvedAt: '2026-05-23T09:00:00Z',
    resolution: 'Slack OAuth token expired. Re-authenticated to fix.',
    messages: [
      { id: 'm67', role: 'customer', content: 'Our Slack integration stopped delivering alert messages to #ops-alerts channel two days ago.', timestamp: '2026-05-22T10:00:00Z' },
      { id: 'm68', role: 'agent', content: 'The Slack OAuth token has expired. Please re-authenticate: go to Integrations > Slack > Re-authorize.', timestamp: '2026-05-22T10:20:00Z' },
      { id: 'm69', role: 'customer', content: 'Re-authorized and messages are flowing again. Thanks.', timestamp: '2026-05-23T09:00:00Z' },
    ],
    tags: ['integrations', 'slack', 'oauth'],
  },
  {
    id: 'TKT-4836',
    customerId: 'CUST-1005',
    subject: 'Custom dashboard widget not rendering',
    category: 'dashboard',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-08-14T18:00:00Z',
    createdAt: '2026-08-12T14:00:00Z',
    updatedAt: '2026-08-13T10:00:00Z',
    resolvedAt: '2026-08-13T10:00:00Z',
    resolution: 'Firefox CSS rendering issue. Applied workaround via specific CSS fix.',
    messages: [
      { id: 'm70', role: 'customer', content: 'My custom dashboard widget shows a blank area where the chart should be. Works in Chrome but not Firefox.', timestamp: '2026-08-12T14:00:00Z' },
      { id: 'm71', role: 'agent', content: 'We have identified a Firefox-specific CSS rendering issue with custom widgets. I have applied a server-side fix. Please hard-refresh (Ctrl+Shift+R).', timestamp: '2026-08-12T14:30:00Z' },
      { id: 'm72', role: 'customer', content: 'Widget is rendering correctly now. Good catch.', timestamp: '2026-08-13T10:00:00Z' },
    ],
    tags: ['dashboard', 'firefox', 'css', 'widget'],
  },
  {
    id: 'TKT-4842',
    customerId: 'CUST-1005',
    subject: 'Data retention policy not applying',
    category: 'compliance',
    status: 'open',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-25T09:00:00Z',
    updatedAt: '2026-09-26T14:00:00Z',
    messages: [
      { id: 'm73', role: 'customer', content: 'Set a 90-day data retention policy but records older than 90 days are still visible. We need this for GDPR compliance.', timestamp: '2026-09-25T09:00:00Z' },
      { id: 'm74', role: 'agent', content: 'The retention policy runs as a nightly batch job. Records set for deletion will be purged in the next cycle. I can trigger an immediate purge if needed.', timestamp: '2026-09-25T09:30:00Z' },
      { id: 'm75', role: 'customer', content: 'Please trigger it immediately. Our compliance audit is next week.', timestamp: '2026-09-26T14:00:00Z' },
    ],
    tags: ['compliance', 'gdpr', 'data-retention'],
  },

  // ── Arjun Reddy ──
  {
    id: 'TKT-4829',
    customerId: 'CUST-1006',
    subject: 'CI/CD pipeline webhook timeout',
    category: 'api',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-06-28T18:00:00Z',
    createdAt: '2026-06-26T11:00:00Z',
    updatedAt: '2026-06-27T08:00:00Z',
    resolvedAt: '2026-06-27T08:00:00Z',
    resolution: 'Increased webhook timeout from 5s to 30s for CI/CD endpoints.',
    messages: [
      { id: 'm76', role: 'customer', content: 'Our CI/CD webhook is timing out. The payload is larger because we added deployment metadata. Need timeout increased.', timestamp: '2026-06-26T11:00:00Z' },
      { id: 'm77', role: 'agent', content: 'Increased your webhook timeout to 30s. Also recommend compressing the payload with gzip for large metadata.', timestamp: '2026-06-26T11:20:00Z' },
      { id: 'm78', role: 'customer', content: 'Working now. Added gzip too, payload dropped 70%.', timestamp: '2026-06-27T08:00:00Z' },
    ],
    tags: ['api', 'webhook', 'cicd', 'timeout'],
  },
  {
    id: 'TKT-4834',
    customerId: 'CUST-1006',
    subject: 'Terraform provider version mismatch',
    category: 'infrastructure',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-07-26T18:00:00Z',
    createdAt: '2026-07-24T08:00:00Z',
    updatedAt: '2026-07-25T09:00:00Z',
    resolvedAt: '2026-07-25T09:00:00Z',
    resolution: 'Terraform provider updated to 3.2.1 to match new API schema.',
    messages: [
      { id: 'm79', role: 'customer', content: 'terraform plan shows errors after your API update. Provider version 3.1.0 seems incompatible.', timestamp: '2026-07-24T08:00:00Z' },
      { id: 'm80', role: 'agent', content: 'Yes, our latest API update requires provider >= 3.2.1. Update your provider version and run terraform init -upgrade.', timestamp: '2026-07-24T08:15:00Z' },
      { id: 'm81', role: 'customer', content: 'Upgraded to 3.2.1, plan runs clean now.', timestamp: '2026-07-25T09:00:00Z' },
    ],
    tags: ['infrastructure', 'terraform', 'api-change'],
  },
  {
    id: 'TKT-4839',
    customerId: 'CUST-1006',
    subject: 'Audit log API returning incomplete data',
    category: 'api',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-20T14:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
    messages: [
      { id: 'm82', role: 'customer', content: 'The audit log API is missing entries for resource deletions. Only creates and updates are returned. We need full audit trail for SOC2.', timestamp: '2026-09-20T14:00:00Z' },
      { id: 'm83', role: 'agent', content: 'Delete events are stored in a separate audit stream. Add ?include_deletes=true to your query parameter.', timestamp: '2026-09-20T14:30:00Z' },
      { id: 'm84', role: 'customer', content: 'That returns them but they are missing the actor field. Who performed the deletion is not recorded.', timestamp: '2026-09-22T10:00:00Z' },
    ],
    tags: ['api', 'audit-log', 'soc2', 'compliance'],
  },
  {
    id: 'TKT-4846',
    customerId: 'CUST-1006',
    subject: 'Custom role permissions not propagating',
    category: 'access-control',
    status: 'open',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-10-01T18:00:00Z',
    createdAt: '2026-09-28T09:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
    messages: [
      { id: 'm85', role: 'customer', content: 'Created a custom role with read-only access to dashboards. Users with this role can still edit. The permission cache might be stale.', timestamp: '2026-09-28T09:00:00Z' },
    ],
    tags: ['access-control', 'permissions', 'roles'],
  },

  // ── Meera Joshi ──
  {
    id: 'TKT-4837',
    customerId: 'CUST-1007',
    subject: 'App freezing on iOS during video calls',
    category: 'mobile',
    status: 'resolved',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-08-18T18:00:00Z',
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-17T11:00:00Z',
    resolvedAt: '2026-08-17T11:00:00Z',
    resolution: 'Memory leak in video rendering on iOS. Patched in hotfix 4.5.1.',
    messages: [
      { id: 'm86', role: 'customer', content: 'The app freezes every time I am on a video call for more than 10 minutes on my iPhone. Have to force quit.', timestamp: '2026-08-16T10:00:00Z' },
      { id: 'm87', role: 'agent', content: 'We identified a memory leak in video rendering on iOS. A hotfix (4.5.1) is available in the App Store. Please update.', timestamp: '2026-08-16T10:30:00Z' },
      { id: 'm88', role: 'customer', content: 'Updated to 4.5.1 and had a 30-minute call with no issues. Thanks!', timestamp: '2026-08-17T11:00:00Z' },
    ],
    tags: ['mobile', 'ios', 'video', 'memory-leak'],
  },
  {
    id: 'TKT-4841',
    customerId: 'CUST-1007',
    subject: 'Calendar sync showing wrong timezone',
    category: 'integrations',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-24T09:00:00Z',
    updatedAt: '2026-09-25T14:00:00Z',
    messages: [
      { id: 'm89', role: 'customer', content: 'My calendar events are showing 5.5 hours off. I think it is using UTC instead of IST.', timestamp: '2026-09-24T09:00:00Z' },
      { id: 'm90', role: 'agent', content: 'Check your timezone setting in Profile > Preferences > Timezone. It should be set to Asia/Kolkata (IST, UTC+5:30).', timestamp: '2026-09-24T09:15:00Z' },
      { id: 'm91', role: 'customer', content: 'It was already set to IST but events from Google Calendar sync are still in UTC. Only synced events are wrong.', timestamp: '2026-09-25T14:00:00Z' },
    ],
    tags: ['integrations', 'calendar', 'timezone'],
  },
  {
    id: 'TKT-4847',
    customerId: 'CUST-1007',
    subject: 'Dark mode text unreadable in chat',
    category: 'usability',
    status: 'open',
    priority: 'low',
    slaStatus: 'within',
    slaDeadline: '2026-10-05T18:00:00Z',
    createdAt: '2026-09-28T13:00:00Z',
    updatedAt: '2026-09-28T13:00:00Z',
    messages: [
      { id: 'm92', role: 'customer', content: 'When I use dark mode, some chat messages have dark grey text on a dark background. Really hard to read.', timestamp: '2026-09-28T13:00:00Z' },
    ],
    tags: ['usability', 'dark-mode', 'accessibility'],
  },

  // ── Karthik Iyer ──
  {
    id: 'TKT-4848',
    customerId: 'CUST-1008',
    subject: 'Email forwarding rules not applying',
    category: 'email',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-08-05T18:00:00Z',
    createdAt: '2026-08-03T10:00:00Z',
    updatedAt: '2026-08-04T09:00:00Z',
    resolvedAt: '2026-08-04T09:00:00Z',
    resolution: 'Forwarding rules had conflicting priority. Resolved by reordering rules.',
    messages: [
      { id: 'm93', role: 'customer', content: 'I set up email forwarding rules but only the first rule fires. The second and third rules are being skipped.', timestamp: '2026-08-03T10:00:00Z' },
      { id: 'm94', role: 'agent', content: 'Email rules execute in order and stop at the first match by default. You need to enable "Continue processing" on rules 1 and 2.', timestamp: '2026-08-03T10:20:00Z' },
      { id: 'm95', role: 'customer', content: 'That did it. All three rules are now applying. Good documentation gap to fix btw.', timestamp: '2026-08-04T09:00:00Z' },
    ],
    tags: ['email', 'rules', 'forwarding'],
  },
  {
    id: 'TKT-4849',
    customerId: 'CUST-1008',
    subject: 'Report scheduling fails silently',
    category: 'reporting',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-09-30T18:00:00Z',
    createdAt: '2026-09-22T11:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
    messages: [
      { id: 'm96', role: 'customer', content: 'Scheduled reports are not being sent. No error messages, they just silently fail. I have three weekly reports configured.', timestamp: '2026-09-22T11:00:00Z' },
      { id: 'm97', role: 'agent', content: 'I can see your scheduled reports. They are failing because the SMTP relay is rejecting them. Check that your custom SMTP settings are still valid.', timestamp: '2026-09-22T11:30:00Z' },
      { id: 'm98', role: 'customer', content: 'SMTP credentials were rotated last week. Updated them but the reports still are not sending.', timestamp: '2026-09-24T10:00:00Z' },
    ],
    tags: ['reporting', 'scheduled', 'smtp', 'email'],
  },
  {
    id: 'TKT-4850',
    customerId: 'CUST-1008',
    subject: 'Bulk import CSV fails validation',
    category: 'import',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-10-02T18:00:00Z',
    createdAt: '2026-09-28T08:00:00Z',
    updatedAt: '2026-09-28T08:00:00Z',
    messages: [
      { id: 'm99', role: 'customer', content: 'Trying to import 5000 contacts via CSV. Validation fails on row 1247 with "invalid date format" but the dates look correct (DD/MM/YYYY).', timestamp: '2026-09-28T08:00:00Z' },
    ],
    tags: ['import', 'csv', 'validation', 'date-format'],
  },

  // ── Sanya Gupta ──
  {
    id: 'TKT-4851',
    customerId: 'CUST-1009',
    subject: 'Cannot change profile picture',
    category: 'account',
    status: 'resolved',
    priority: 'low',
    slaStatus: 'within',
    slaDeadline: '2026-07-20T18:00:00Z',
    createdAt: '2026-07-18T10:00:00Z',
    updatedAt: '2026-07-18T11:00:00Z',
    resolvedAt: '2026-07-18T11:00:00Z',
    resolution: 'Image was too large. Compressed and re-uploaded successfully.',
    messages: [
      { id: 'm100', role: 'customer', content: 'I keep trying to change my profile picture but nothing happens after I select the photo.', timestamp: '2026-07-18T10:00:00Z' },
      { id: 'm101', role: 'agent', content: 'Profile pictures need to be under 5MB. Your photo might be too large. Try using a smaller image or our built-in crop tool.', timestamp: '2026-07-18T10:15:00Z' },
      { id: 'm102', role: 'customer', content: 'Oh it was 12MB! Cropped it and it worked. Thanks!', timestamp: '2026-07-18T11:00:00Z' },
    ],
    tags: ['account', 'profile', 'image-upload'],
  },
  {
    id: 'TKT-4852',
    customerId: 'CUST-1009',
    subject: 'Forgot password email not arriving',
    category: 'authentication',
    status: 'open',
    priority: 'high',
    slaStatus: 'warning',
    slaDeadline: '2026-09-29T18:00:00Z',
    createdAt: '2026-09-28T07:00:00Z',
    updatedAt: '2026-09-28T07:00:00Z',
    messages: [
      { id: 'm103', role: 'customer', content: 'I forgot my password and clicked the reset link but I never got the email. I checked spam too. My email is sanya.gupta@example.com.', timestamp: '2026-09-28T07:00:00Z' },
    ],
    tags: ['authentication', 'password-reset', 'email'],
  },

  // ── Rohan Das ──
  {
    id: 'TKT-4853',
    customerId: 'CUST-1010',
    subject: 'Search indexing delay for new records',
    category: 'search',
    status: 'resolved',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-08-22T18:00:00Z',
    createdAt: '2026-08-20T09:00:00Z',
    updatedAt: '2026-08-21T10:00:00Z',
    resolvedAt: '2026-08-21T10:00:00Z',
    resolution: 'Search index was backlogged. Triggered reindex. Normal delay is 30s, was 15min.',
    messages: [
      { id: 'm104', role: 'customer', content: 'New records I create are not showing up in search for about 15 minutes. Used to be near-instant.', timestamp: '2026-08-20T09:00:00Z' },
      { id: 'm105', role: 'agent', content: 'The search index had a backlog. I triggered a reindex. Normal indexing latency is ~30 seconds. Should be back to normal now.', timestamp: '2026-08-20T09:30:00Z' },
      { id: 'm106', role: 'customer', content: 'Confirmed, new records appear in search within 30 seconds now.', timestamp: '2026-08-21T10:00:00Z' },
    ],
    tags: ['search', 'indexing', 'performance'],
  },
  {
    id: 'TKT-4854',
    customerId: 'CUST-1010',
    subject: 'API key rotation broke all integrations',
    category: 'api',
    status: 'resolved',
    priority: 'critical',
    slaStatus: 'within',
    slaDeadline: '2026-09-16T18:00:00Z',
    createdAt: '2026-09-14T07:00:00Z',
    updatedAt: '2026-09-14T09:00:00Z',
    resolvedAt: '2026-09-14T09:00:00Z',
    resolution: 'Previous key had a 24h grace period. Restored old key temporarily while user updated integrations.',
    messages: [
      { id: 'm107', role: 'customer', content: 'Rotated my API key and now 5 integrations are broken. Is there a grace period for the old key?', timestamp: '2026-09-14T07:00:00Z' },
      { id: 'm108', role: 'agent', content: 'There is a 24-hour grace period. I have restored your previous key temporarily. You have 24 hours to update all integrations with the new key.', timestamp: '2026-09-14T07:20:00Z' },
      { id: 'm109', role: 'customer', content: 'All integrations updated. You can expire the old key now.', timestamp: '2026-09-14T09:00:00Z' },
    ],
    tags: ['api', 'key-rotation', 'integrations'],
  },
  {
    id: 'TKT-4855',
    customerId: 'CUST-1010',
    subject: 'Custom field formula returning #ERROR',
    category: 'customization',
    status: 'open',
    priority: 'medium',
    slaStatus: 'within',
    slaDeadline: '2026-10-01T18:00:00Z',
    createdAt: '2026-09-27T14:00:00Z',
    updatedAt: '2026-09-28T10:00:00Z',
    messages: [
      { id: 'm110', role: 'customer', content: 'My custom field formula =SUM(line_items.amount) is returning #ERROR on all records. It was working last week.', timestamp: '2026-09-27T14:00:00Z' },
      { id: 'm111', role: 'agent', content: 'The formula engine was updated. SUM now requires the full path: =SUM(record.line_items[*].amount). Let me know if that resolves it.', timestamp: '2026-09-27T14:30:00Z' },
      { id: 'm112', role: 'customer', content: 'Updated the formula but now it returns 0 instead of the actual sum. The line_items array is not empty.', timestamp: '2026-09-28T10:00:00Z' },
    ],
    tags: ['customization', 'formulas', 'fields'],
  },

  // ── Lakshmi Venkat ──
  {
    id: 'TKT-4856',
    customerId: 'CUST-1011',
    subject: 'SSO login redirect loop',
    category: 'authentication',
    status: 'resolved',
    priority: 'critical',
    slaStatus: 'within',
    slaDeadline: '2026-06-18T18:00:00Z',
    createdAt: '2026-06-16T08:00:00Z',
    updatedAt: '2026-06-16T10:00:00Z',
    resolvedAt: '2026-06-16T10:00:00Z',
    resolution: 'SSO redirect URI mismatch. Updated to include trailing slash.',
    messages: [
      { id: 'm113', role: 'customer', content: 'None of our team can log in. We get stuck in a redirect loop after SSO authentication.', timestamp: '2026-06-16T08:00:00Z' },
      { id: 'm114', role: 'agent', content: 'I see a redirect URI mismatch. Your SSO config has the callback URL without a trailing slash. Updating it now.', timestamp: '2026-06-16T08:15:00Z' },
      { id: 'm115', role: 'customer', content: 'Login working for the whole team now. That was fast, thank you.', timestamp: '2026-06-16T10:00:00Z' },
    ],
    tags: ['authentication', 'sso', 'redirect', 'enterprise'],
  },
  {
    id: 'TKT-4857',
    customerId: 'CUST-1011',
    subject: 'Compliance report missing encryption status',
    category: 'compliance',
    status: 'open',
    priority: 'high',
    slaStatus: 'within',
    slaDeadline: '2026-10-01T18:00:00Z',
    createdAt: '2026-09-26T10:00:00Z',
    updatedAt: '2026-09-27T09:00:00Z',
    messages: [
      { id: 'm116', role: 'customer', content: 'Our compliance report PDF is missing the data encryption status section. We need this for our quarterly SOC2 review.', timestamp: '2026-09-26T10:00:00Z' },
      { id: 'm117', role: 'agent', content: 'The encryption status section was moved to a separate "Security Posture" report in the last update. You can find it under Reports > Security Posture.', timestamp: '2026-09-26T10:30:00Z' },
      { id: 'm118', role: 'customer', content: 'Found it. But our auditors expect a single consolidated report. Can you merge them?', timestamp: '2026-09-27T09:00:00Z' },
    ],
    tags: ['compliance', 'soc2', 'reporting', 'enterprise'],
  },

  // ── Amit Saxena ──
  {
    id: 'TKT-4858',
    customerId: 'CUST-1012',
    subject: 'Mobile app payment declined but money deducted',
    category: 'payments',
    status: 'resolved',
    priority: 'critical',
    slaStatus: 'within',
    slaDeadline: '2026-08-28T18:00:00Z',
    createdAt: '2026-08-26T09:00:00Z',
    updatedAt: '2026-08-27T10:00:00Z',
    resolvedAt: '2026-08-27T10:00:00Z',
    resolution: 'Payment was captured but order creation failed. Refund initiated and order manually created.',
    messages: [
      { id: 'm119', role: 'customer', content: 'I tried to pay for my subscription and the app said payment failed, but my bank shows the money was deducted!', timestamp: '2026-08-26T09:00:00Z' },
      { id: 'm120', role: 'agent', content: 'I can see the payment was captured but the order creation step failed due to a timeout. I have two options: initiate a full refund, or manually create your order. Which would you prefer?', timestamp: '2026-08-26T09:15:00Z' },
      { id: 'm121', role: 'customer', content: 'Please create the order. I need the subscription active.', timestamp: '2026-08-26T09:30:00Z' },
      { id: 'm122', role: 'agent', content: 'Done. Your subscription is now active and the payment is linked. You should see the confirmation email shortly.', timestamp: '2026-08-26T09:45:00Z' },
      { id: 'm123', role: 'customer', content: 'Got the email. Thank you for the quick resolution.', timestamp: '2026-08-27T10:00:00Z' },
    ],
    tags: ['payments', 'mobile', 'subscription', 'order-failure'],
  },
  {
    id: 'TKT-4859',
    customerId: 'CUST-1012',
    subject: 'App notification sound not customizable',
    category: 'mobile',
    status: 'open',
    priority: 'low',
    slaStatus: 'within',
    slaDeadline: '2026-10-05T18:00:00Z',
    createdAt: '2026-09-28T10:00:00Z',
    updatedAt: '2026-09-28T10:00:00Z',
    messages: [
      { id: 'm124', role: 'customer', content: 'Is there a way to change the notification sound? The default one sounds like every other app on my phone.', timestamp: '2026-09-28T10:00:00Z' },
    ],
    tags: ['mobile', 'notifications', 'customization', 'feature-request'],
  },
];

// ─── Episodic Memory ─────────────────────────────────────────────────────────

export const episodicMemories: EpisodicMemory[] = [
  // Priya
  { id: 'ep-1', customerId: 'CUST-1001', ticketId: 'TKT-4818', event: 'First billing sync failure', outcome: 'Resolved by forcing billing cache clear and sync', timestamp: '2026-04-10T09:15:00Z' },
  { id: 'ep-2', customerId: 'CUST-1001', ticketId: 'TKT-4821', event: 'Second billing sync failure after plan upgrade', outcome: 'Cache clear failed. Re-linking failed. Escalated — webhook race condition found.', timestamp: '2026-05-15T10:00:00Z', emotionalContext: 'Growing frustration' },
  { id: 'ep-3', customerId: 'CUST-1001', ticketId: 'TKT-4830', event: 'Third billing sync failure', outcome: 'Applied server-side billing reconciliation script. Different root cause.', timestamp: '2026-07-02T08:00:00Z', emotionalContext: 'Angry, losing patience' },
  { id: 'ep-4', customerId: 'CUST-1001', ticketId: 'TKT-4845', event: 'Fourth billing sync failure', outcome: 'Pending — customer threatening to churn', timestamp: '2026-09-28T14:00:00Z', emotionalContext: 'Very frustrated, churn risk' },
  { id: 'ep-5', customerId: 'CUST-1001', ticketId: 'TKT-4819', event: 'Dashboard loading slowly', outcome: 'CDN cache invalidated', timestamp: '2026-04-18T11:00:00Z' },
  { id: 'ep-6', customerId: 'CUST-1001', ticketId: 'TKT-4822', event: 'CSV export missing columns after upgrade', outcome: 'Column mapping reset, re-configured', timestamp: '2026-05-30T09:00:00Z' },
  { id: 'ep-7', customerId: 'CUST-1001', ticketId: 'TKT-4835', event: '2FA codes not sending', outcome: 'Switched to authenticator app', timestamp: '2026-08-10T07:00:00Z' },
  // Rahul
  { id: 'ep-8', customerId: 'CUST-1002', ticketId: 'TKT-4823', event: 'API rate limiting mismatch', outcome: 'Updated docs, increased rate limit to 1200', timestamp: '2026-05-18T14:00:00Z' },
  { id: 'ep-9', customerId: 'CUST-1002', ticketId: 'TKT-4826', event: 'Webhook signatures failing', outcome: 'Secret was auto-rotated, new secret provided', timestamp: '2026-06-12T09:00:00Z' },
  { id: 'ep-10', customerId: 'CUST-1002', ticketId: 'TKT-4831', event: 'GraphQL performance degradation', outcome: 'Query optimization with field selection and pagination', timestamp: '2026-07-10T15:00:00Z' },
  // Vikram
  { id: 'ep-11', customerId: 'CUST-1004', ticketId: 'TKT-4824', event: 'App crash on Android 16', outcome: 'Updated from v4.2 to v4.3', timestamp: '2026-05-20T08:00:00Z' },
  { id: 'ep-12', customerId: 'CUST-1004', ticketId: 'TKT-4833', event: 'Notifications stopped after v4.5 update', outcome: 'Re-enabled permissions and disabled battery optimization', timestamp: '2026-07-20T09:00:00Z' },
  { id: 'ep-13', customerId: 'CUST-1004', ticketId: 'TKT-4838', event: 'Photo uploads broken', outcome: 'Storage permission re-granted after update', timestamp: '2026-08-25T11:00:00Z' },
];

// ─── Semantic Memory ─────────────────────────────────────────────────────────

export const semanticMemories: SemanticMemory[] = [
  // Priya
  { id: 'sem-1', customerId: 'CUST-1001', category: 'environment', key: 'Operating System', value: 'Windows 11', confidence: 1.0, lastUpdated: '2026-09-28T14:00:00Z' },
  { id: 'sem-2', customerId: 'CUST-1001', category: 'environment', key: 'Browser', value: 'Chrome 140', confidence: 1.0, lastUpdated: '2026-09-28T14:00:00Z' },
  { id: 'sem-3', customerId: 'CUST-1001', category: 'plan', key: 'Current Plan', value: 'Business (upgraded from Starter)', confidence: 1.0, lastUpdated: '2026-05-15T10:00:00Z' },
  { id: 'sem-4', customerId: 'CUST-1001', category: 'product', key: 'App Version', value: '4.5.2', confidence: 1.0, lastUpdated: '2026-09-28T14:00:00Z' },
  { id: 'sem-5', customerId: 'CUST-1001', category: 'preference', key: 'Communication Style', value: 'Prefers concise responses, does not like repeating information', confidence: 0.95, lastUpdated: '2026-07-02T08:00:00Z' },
  { id: 'sem-6', customerId: 'CUST-1001', category: 'fact', key: 'Recurring Issue', value: 'Billing sync has failed 4 times over 6 months', confidence: 1.0, lastUpdated: '2026-09-28T14:00:00Z' },
  // Rahul
  { id: 'sem-7', customerId: 'CUST-1002', category: 'environment', key: 'Operating System', value: 'macOS 15.2', confidence: 1.0, lastUpdated: '2026-09-27T10:00:00Z' },
  { id: 'sem-8', customerId: 'CUST-1002', category: 'preference', key: 'Communication Style', value: 'Prefers detailed technical explanations with code examples', confidence: 0.95, lastUpdated: '2026-07-10T15:00:00Z' },
  { id: 'sem-9', customerId: 'CUST-1002', category: 'fact', key: 'Technical Level', value: 'Power user — provides test scripts, understands HMAC, GraphQL optimization', confidence: 1.0, lastUpdated: '2026-07-10T15:00:00Z' },
  // Vikram
  { id: 'sem-10', customerId: 'CUST-1004', category: 'environment', key: 'Device', value: 'Pixel 9, Android 16', confidence: 1.0, lastUpdated: '2026-09-28T12:00:00Z' },
  { id: 'sem-11', customerId: 'CUST-1004', category: 'environment', key: 'App Version', value: '4.2.0 (outdated — updates caused multiple issues)', confidence: 0.9, lastUpdated: '2026-09-28T12:00:00Z' },
  { id: 'sem-12', customerId: 'CUST-1004', category: 'preference', key: 'Communication Style', value: 'Non-technical, prefers phone, needs simple step-by-step guidance', confidence: 0.95, lastUpdated: '2026-08-25T11:00:00Z' },
  { id: 'sem-13', customerId: 'CUST-1004', category: 'fact', key: 'Update History', value: 'App updates from 4.2→4.3→4.5 caused crash, notification, and permission issues', confidence: 1.0, lastUpdated: '2026-09-28T12:00:00Z' },
];

// ─── Procedural Memory (Winning & Failed) ────────────────────────────────────

export const proceduralMemories: ProceduralMemory[] = [
  // Priya billing sync attempts
  { id: 'proc-1', customerId: 'CUST-1001', category: 'billing-sync', step: 'Clear billing cache and force sync', outcome: 'success', ticketId: 'TKT-4818', timestamp: '2026-04-10T09:22:00Z', context: 'Worked on first occurrence' },
  { id: 'proc-2', customerId: 'CUST-1001', category: 'billing-sync', step: 'Clear billing cache and force sync', outcome: 'failure', ticketId: 'TKT-4821', timestamp: '2026-05-15T10:10:00Z', context: 'Did not work on second occurrence after plan upgrade' },
  { id: 'proc-3', customerId: 'CUST-1001', category: 'billing-sync', step: 'Re-link payment method', outcome: 'failure', ticketId: 'TKT-4821', timestamp: '2026-05-15T10:35:00Z', context: 'Did not resolve the sync issue' },
  { id: 'proc-4', customerId: 'CUST-1001', category: 'billing-sync', step: 'Escalate to billing team for webhook fix', outcome: 'success', ticketId: 'TKT-4821', timestamp: '2026-05-16T16:00:00Z', context: 'Found webhook race condition' },
  { id: 'proc-5', customerId: 'CUST-1001', category: 'billing-sync', step: 'Apply server-side billing reconciliation script', outcome: 'success', ticketId: 'TKT-4830', timestamp: '2026-07-02T09:30:00Z', context: 'Worked but not a permanent fix' },
  // Vikram
  { id: 'proc-6', customerId: 'CUST-1004', category: 'app-crash', step: 'Update app to latest version', outcome: 'success', ticketId: 'TKT-4824', timestamp: '2026-05-21T10:00:00Z' },
  { id: 'proc-7', customerId: 'CUST-1004', category: 'notifications', step: 'Re-enable notification permissions in settings', outcome: 'failure', ticketId: 'TKT-4833', timestamp: '2026-07-20T09:15:00Z', context: 'Permissions alone did not fix it' },
  { id: 'proc-8', customerId: 'CUST-1004', category: 'notifications', step: 'Disable battery optimization for the app', outcome: 'success', ticketId: 'TKT-4833', timestamp: '2026-07-21T10:15:00Z' },
  { id: 'proc-9', customerId: 'CUST-1004', category: 'permissions', step: 'Re-grant storage/camera permissions after app update', outcome: 'success', ticketId: 'TKT-4838', timestamp: '2026-08-25T11:15:00Z' },
];

// ─── Winning Fixes ───────────────────────────────────────────────────────────

export const winningFixes: WinningFix[] = [
  { id: 'wf-1', category: 'billing-sync', step: 'Escalate to billing team for webhook investigation', successCount: 1, lastUsed: '2026-05-16T16:00:00Z', context: 'When cache clear and re-link both fail', ticketIds: ['TKT-4821'] },
  { id: 'wf-2', category: 'billing-sync', step: 'Apply server-side billing reconciliation script', successCount: 1, lastUsed: '2026-07-02T09:30:00Z', context: 'Direct server intervention when other methods fail', ticketIds: ['TKT-4830'] },
  { id: 'wf-3', category: 'app-crash', step: 'Update to latest app version', successCount: 3, lastUsed: '2026-08-17T11:00:00Z', context: 'Most mobile issues resolved by updating', ticketIds: ['TKT-4824', 'TKT-4837'] },
  { id: 'wf-4', category: 'notifications', step: 'Disable battery optimization + re-enable permissions', successCount: 2, lastUsed: '2026-07-22T16:00:00Z', context: 'Android notification fix requires both steps', ticketIds: ['TKT-4833'] },
  { id: 'wf-5', category: 'permissions', step: 'Re-grant app permissions after update', successCount: 2, lastUsed: '2026-08-26T09:00:00Z', context: 'App updates reset Android permissions', ticketIds: ['TKT-4838'] },
  { id: 'wf-6', category: 'browser-extension', step: 'Disable conflicting browser extension', successCount: 2, lastUsed: '2026-06-20T11:00:00Z', context: 'Ad-blockers cause PAY-204 checkout errors', ticketIds: ['TKT-4820', 'TKT-4828'] },
];

// ─── Failed Solutions ────────────────────────────────────────────────────────

export const failedSolutions: FailedSolution[] = [
  { id: 'fs-1', customerId: 'CUST-1001', category: 'billing-sync', step: 'Clear billing cache and force sync', failureReason: 'Did not work on second and subsequent occurrences after plan upgrade', ticketId: 'TKT-4821', timestamp: '2026-05-15T10:30:00Z' },
  { id: 'fs-2', customerId: 'CUST-1001', category: 'billing-sync', step: 'Re-link payment method', failureReason: 'Payment re-link did not resolve sync issue — root cause was deeper', ticketId: 'TKT-4821', timestamp: '2026-05-15T11:00:00Z' },
  { id: 'fs-3', customerId: 'CUST-1004', category: 'notifications', step: 'Re-enable notification permissions only', failureReason: 'Permissions alone insufficient; battery optimization also needed', ticketId: 'TKT-4833', timestamp: '2026-07-20T09:15:00Z' },
];

// ─── Affective Memory ────────────────────────────────────────────────────────

export const affectiveMemories: AffectiveMemory[] = [
  {
    id: 'aff-1',
    customerId: 'CUST-1001',
    frustrationLevel: 9 as FrustrationLevel,
    frustrationTrajectory: [
      { timestamp: '2026-04-10T09:15:00Z', level: 3 as FrustrationLevel, trigger: 'First billing sync issue', ticketId: 'TKT-4818' },
      { timestamp: '2026-05-15T10:00:00Z', level: 5 as FrustrationLevel, trigger: 'Second billing sync failure', ticketId: 'TKT-4821' },
      { timestamp: '2026-05-15T11:00:00Z', level: 7 as FrustrationLevel, trigger: 'Two fixes failed in a row', ticketId: 'TKT-4821' },
      { timestamp: '2026-07-02T08:00:00Z', level: 8 as FrustrationLevel, trigger: 'Third billing sync failure', ticketId: 'TKT-4830' },
      { timestamp: '2026-09-28T14:00:00Z', level: 9 as FrustrationLevel, trigger: 'Fourth billing sync failure, threatening to churn', ticketId: 'TKT-4845' },
    ],
    communicationPreferences: { preferredChannel: 'chat', technicalLevel: 'intermediate', preferredTone: 'concise', language: 'en' },
    sentiment: 'angry',
    lastUpdated: '2026-09-28T14:00:00Z',
  },
  {
    id: 'aff-2',
    customerId: 'CUST-1002',
    frustrationLevel: 1 as FrustrationLevel,
    frustrationTrajectory: [
      { timestamp: '2026-05-18T14:00:00Z', level: 2 as FrustrationLevel, trigger: 'Rate limit docs wrong', ticketId: 'TKT-4823' },
      { timestamp: '2026-05-19T11:00:00Z', level: 0 as FrustrationLevel, trigger: 'Quick resolution, limit increased', ticketId: 'TKT-4823' },
      { timestamp: '2026-06-12T09:00:00Z', level: 2 as FrustrationLevel, trigger: 'Webhook secret rotated without notice', ticketId: 'TKT-4826' },
      { timestamp: '2026-06-13T10:00:00Z', level: 1 as FrustrationLevel, trigger: 'Resolved promptly', ticketId: 'TKT-4826' },
    ],
    communicationPreferences: { preferredChannel: 'email', technicalLevel: 'power-user', preferredTone: 'detailed', language: 'en' },
    sentiment: 'positive',
    lastUpdated: '2026-09-27T10:00:00Z',
  },
  {
    id: 'aff-3',
    customerId: 'CUST-1004',
    frustrationLevel: 6 as FrustrationLevel,
    frustrationTrajectory: [
      { timestamp: '2026-05-20T08:00:00Z', level: 5 as FrustrationLevel, trigger: 'App crash, cannot use at all', ticketId: 'TKT-4824' },
      { timestamp: '2026-05-21T10:00:00Z', level: 3 as FrustrationLevel, trigger: 'Resolved with update', ticketId: 'TKT-4824' },
      { timestamp: '2026-06-08T15:30:00Z', level: 4 as FrustrationLevel, trigger: 'Settings moved after update', ticketId: 'TKT-4827' },
      { timestamp: '2026-07-20T09:00:00Z', level: 6 as FrustrationLevel, trigger: 'Notifications broken after another update', ticketId: 'TKT-4833' },
      { timestamp: '2026-08-25T11:00:00Z', level: 6 as FrustrationLevel, trigger: 'Photos broken after update — pattern of updates breaking things', ticketId: 'TKT-4838' },
    ],
    communicationPreferences: { preferredChannel: 'phone', technicalLevel: 'non-technical', preferredTone: 'casual', language: 'en' },
    sentiment: 'negative',
    lastUpdated: '2026-09-28T12:00:00Z',
  },
];

// ─── Analytics (simulated demo data) ─────────────────────────────────────────

export const analyticsData: AnalyticsData = {
  totalTickets: 42,
  resolvedTickets: 31,
  avgResolutionTime: 18.5,
  avgFrustrationReduction: 3.2,
  memoryHits: 156,
  repeatQuestionsPrevented: 89,
  timeSavedMinutes: 847,
  customerSatisfaction: 94,
  ticketsOverTime: [
    { date: '2026-04', count: 5 },
    { date: '2026-05', count: 8 },
    { date: '2026-06', count: 6 },
    { date: '2026-07', count: 7 },
    { date: '2026-08', count: 9 },
    { date: '2026-09', count: 7 },
  ],
  frustrationOverTime: [
    { date: '2026-04', avg: 3.2 },
    { date: '2026-05', avg: 4.1 },
    { date: '2026-06', avg: 3.8 },
    { date: '2026-07', avg: 4.5 },
    { date: '2026-08', avg: 3.9 },
    { date: '2026-09', avg: 4.2 },
  ],
  topCategories: [
    { category: 'Mobile', count: 9 },
    { category: 'API', count: 7 },
    { category: 'Billing', count: 6 },
    { category: 'Authentication', count: 5 },
    { category: 'Integrations', count: 4 },
    { category: 'Export', count: 3 },
    { category: 'Compliance', count: 3 },
    { category: 'Other', count: 5 },
  ],
  memoryUtilization: [
    { layer: 'Episodic', count: 45, hitRate: 92 },
    { layer: 'Semantic', count: 38, hitRate: 88 },
    { layer: 'Procedural', count: 24, hitRate: 95 },
    { layer: 'Affective', count: 18, hitRate: 85 },
  ],
};
